#111 Update services and actions for opportunities
BinaryStudioAcademy/bsa-winter-2022-growup pull request #108
Opened 2022-03-16 11:10 UTC by Karyna-Kharina

2022-03-16 22:11 UTC, aleksandr-kuharenko requested changes

2022-03-16 22:11 UTC, aleksandr-kuharenko commented on frontend/src/store/opportunities/actions.ts
> +      id: result[0].id,
what if `result` is empty array?

2022-03-17 13:59 UTC, Alexandr21Smirnov approved these changes

2022-03-18 09:54 UTC, nikita-remeslov approved these changes

2022-03-18 09:54 UTC, nikita-remeslov commented
@Karyna-Kharina Conflicts

2022-03-18 10:46 UTC, merged