#98 Fix/first time logged
BinaryStudioAcademy/bsa-winter-2022-growup pull request #110
Opened 2022-03-16 16:30 UTC by deimonbody

2022-03-16 22:09 UTC, aleksandr-kuharenko requested changes

2022-03-16 22:09 UTC, aleksandr-kuharenko commented on frontend/src/components/main-page/main-page.tsx
> +      if (!user?.firstName) {
you already checked that user is not null
```suggestion
      if (!user.firstName) {
```

2022-03-16 22:09 UTC, aleksandr-kuharenko commented on frontend/src/components/main-page/main-page.tsx
> +      if (!user?.isCompleteTest) {
```suggestion
      if (!user.isCompleteTest) {
```

2022-03-16 22:09 UTC, aleksandr-kuharenko commented on frontend/src/components/okr/tabs/two-tabs.tsx
> +      if (!user?.isCompleteTest) {
```suggestion
      if (!user.firstName) {
        navigate(`${MentorMenteeRoute.SETTINGS_PROFILE}/1`);
        return;
      }
      if (!user.isCompleteTest) {
```

2022-03-16 22:09 UTC, aleksandr-kuharenko commented on frontend/src/components/opportunities-page/opportunities-page.tsx
> +      if (!user?.isCompleteTest) {
```suggestion
      if (!user.firstName) {
        navigate(`${MentorMenteeRoute.SETTINGS_PROFILE}/1`);
        return;
      }
      if (!user.isCompleteTest) {
```

2022-03-16 22:09 UTC, aleksandr-kuharenko commented on frontend/src/components/profile-settings/steps/first-step.tsx
> +// }
remove comments

2022-03-16 22:09 UTC, aleksandr-kuharenko commented on frontend/src/components/profile/profile.tsx
> +      }
can we move this repeated logic to separate function and reuse in all files?

2022-03-17 10:54 UTC, AndriyCh1 approved these changes

2022-03-18 09:55 UTC, nikita-remeslov reviewed
conflicts

2022-03-18 10:48 UTC, nikita-remeslov approved these changes

2022-03-18 10:48 UTC, merged