feat: add select skills #136
BinaryStudioAcademy/bsa-winter-2022-growup pull request #127
Opened 2022-03-19 22:27 UTC by twistedomelette

2022-03-20 19:20 UTC, aleksandr-kuharenko requested changes

2022-03-20 19:20 UTC, aleksandr-kuharenko commented on frontend/src/components/skills/skill-overview.tsx
> +                if (skill.name && selectSkills !== 'unimportant')
move literal to const

2022-03-21 11:38 UTC, aleksandr-kuharenko approved these changes

2022-03-21 11:55 UTC, Karyna-Kharina approved these changes

2022-03-21 12:32 UTC, merged