modify validateBody
BinaryStudioAcademy/bsa-winter-2022-growup pull request #135
Opened 2022-03-21 16:33 UTC by Pavel1066

2022-03-21 16:50 UTC, aleksandr-kuharenko requested changes

2022-03-21 16:50 UTC, aleksandr-kuharenko commented on backend/src/api/middlewares/validation-middleware.ts
> +      return;
return next(newError)

2022-03-22 09:33 UTC, nikita-remeslov approved these changes

2022-03-22 17:26 UTC, aleksandr-kuharenko approved these changes

2022-03-22 17:30 UTC, merged