#121 Feaut/delete user eddit role
BinaryStudioAcademy/bsa-winter-2022-growup pull request #137
Opened 2022-03-22 09:58 UTC by deimonbody

2022-03-22 13:55 UTC, nikita-remeslov approved these changes

2022-03-22 13:55 UTC, nikita-remeslov commented on frontend/src/components/admin/styles.scss
> +  @media screen and (max-width: 767px) {
You can use bootstrap breakpoints

2022-03-22 13:55 UTC, nikita-remeslov commented on backend/src/data/seeders/index.ts
> +// import CompanySeeder from './company.seeder';
?

2022-03-22 13:55 UTC, nikita-remeslov commented on backend/src/data/seeders/index.ts
> +  // await CompanySeeder.execute();
?

2022-03-22 13:57 UTC, nikita-remeslov requested changes
Resolve comments

2022-03-22 17:32 UTC, aleksandr-kuharenko requested changes

2022-03-22 17:32 UTC, aleksandr-kuharenko commented on backend/src/services/user.service.ts
> +  userInstance.remove();
```suggestion
  await userRoleInstance[0].remove();
  await userInstance.remove();
```

2022-03-22 17:32 UTC, aleksandr-kuharenko commented on backend/src/services/user.service.ts
> +  userRoleInstance[0].save();
```suggestion
  await userRoleInstance[0].save();
```

2022-03-22 17:32 UTC, aleksandr-kuharenko commented on backend/src/services/user.service.ts
> +): Promise<any> => {
remove any

2022-03-23 08:47 UTC, nikita-remeslov approved these changes

2022-03-23 10:22 UTC, AndriyCh1 approved these changes

2022-03-23 20:35 UTC, merged