add not found page
BinaryStudioAcademy/bsa-winter-2022-growup pull request #14
Opened 2022-02-09 11:30 UTC by Pavel1066

2022-02-09 12:31 UTC, aleksandr-kuharenko requested changes
Check error in the failed build and fix it.

2022-02-09 12:31 UTC, aleksandr-kuharenko commented on frontend/src/index.tsx
> +//import App from 'components/app/app';
All existing routing is broken. Only 404 page is shown.

2022-02-09 13:45 UTC, nikita-remeslov requested changes
Need changes

2022-02-09 13:45 UTC, nikita-remeslov commented on frontend/src/components/notFound/notFoundStyle.scss
> +  display: flex;
You can use bootstrap for most of these custom styles. Try to use bootstrap classes instead of custom styles

2022-02-09 13:45 UTC, nikita-remeslov commented on frontend/src/components/app/app.tsx
> +  const isIncludePath = Object.values(AppRoute).includes(pathname as AppRoute);
redundant logic, you can use standard router flow - https://www.w3schools.com/react/react_router.asp

2022-02-09 13:45 UTC, nikita-remeslov commented on frontend/src/components/notFound/NotFound.tsx
> +import { Button } from 'react-bootstrap';
Check out the naming principle in the project.
The same for the style file naming.

2022-02-09 13:45 UTC, nikita-remeslov commented on frontend/src/components/notFound/notFoundStyle.scss
> +.not_found {
you have only one style file. Should name it just `styles.scss`

2022-02-09 18:40 UTC, nikita-remeslov commented on frontend/src/components/notFound/notFoundStyle.scss
> +  display: flex;
Not fixed

2022-02-09 18:41 UTC, nikita-remeslov commented
Also, fix linter error that shows in CI process

2022-02-10 21:56 UTC, aleksandr-kuharenko approved these changes

2022-02-11 07:32 UTC, nikita-remeslov requested changes

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +  width: 100%;
bootstrap - `w-100`

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +  display: flex;
bootstrap - `d-flex`

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +  align-items: center;
align-items-center

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +    flex-direction: column;
flex-column

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +      font-size: 15rem;
use our default font size

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +      -webkit-background-clip: text;
this selector is redundant

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +      -webkit-text-fill-color: transparent;
this selector is redundant

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +      color: #495057;
try to use our default colors

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +      margin-bottom: 0.5rem;
bootstrap class - mb-2

2022-02-11 07:32 UTC, nikita-remeslov commented on frontend/src/components/not-found/styles.scss
> +.card {
check the whole file
https://getbootstrap.com/docs/5.0/getting-started/introduction/

2022-02-11 11:53 UTC, aleksandr-kuharenko approved these changes

2022-02-11 11:53 UTC, merged