New/profile endpoint #118
BinaryStudioAcademy/bsa-winter-2022-growup pull request #140
Opened 2022-03-22 13:13 UTC by twistedomelette

2022-03-22 17:41 UTC, aleksandr-kuharenko requested changes
add new endpoint to swagger

2022-03-22 17:41 UTC, aleksandr-kuharenko commented on backend/src/services/user.service.ts
> +  user.save();
```suggestion
  await user.save();
```

2022-03-22 17:41 UTC, aleksandr-kuharenko commented on backend/src/data/entities/user.ts
> +  @ManyToMany(() => Tags, (tag) => tag.opportunities)
are you sure it should be `tag.opportunities` here?

2022-03-23 08:49 UTC, nikita-remeslov approved these changes

2022-03-24 08:32 UTC, aleksandr-kuharenko approved these changes

2022-03-24 08:58 UTC, merged