#139 Form show password fixed
BinaryStudioAcademy/bsa-winter-2022-growup pull request #141
Opened 2022-03-22 14:42 UTC by Werfit

Besides fixing bug with show password button, I also added `type` field to common button element as well as renamed property onSubmit to onClick

2022-03-22 19:16 UTC, aleksandr-kuharenko requested changes

2022-03-22 19:16 UTC, aleksandr-kuharenko commented on frontend/src/helpers/check-is-first-logged/index.ts
> +  // }
revert

2022-03-22 19:18 UTC, aleksandr-kuharenko requested changes

2022-03-22 19:18 UTC, aleksandr-kuharenko commented on frontend/src/components/profile-settings/steps/styles.scss
> +// }
?

2022-03-22 19:20 UTC, aleksandr-kuharenko approved these changes

2022-03-23 08:51 UTC, nikita-remeslov approved these changes

2022-03-23 08:52 UTC, nikita-remeslov commented
@Werfit Resolve conflicts please and after that you can merge this PR

2022-03-23 08:57 UTC, merged