#19 Admin Home Page Scaffold
BinaryStudioAcademy/bsa-winter-2022-growup pull request #15
Opened 2022-02-09 14:26 UTC by Werfit

2022-02-09 18:46 UTC, nikita-remeslov commented on frontend/src/components/admin/admin.tsx
> +              <Link to={AppRoute.ADMIN}>
If you use html you can avoid some custom styles. 
Use html elements with bootstrap classes

2022-02-09 18:46 UTC, nikita-remeslov requested changes
Overall looks good. Need to fix 1 comment

2022-02-09 20:50 UTC, Werfit commented
If I understood correctly, I should have remove **Nav.Link** and add class **nav-link** to the **AppLink** component. So I did this

2022-02-10 08:51 UTC, nikita-remeslov approved these changes

2022-02-10 08:51 UTC, merged