#121 Fix/delete users by admin
BinaryStudioAcademy/bsa-winter-2022-growup pull request #158
Opened 2022-03-24 10:52 UTC by deimonbody

The view of buttons was changed.New migration to delete user field in all tables (if there were contections)

2022-03-24 10:59 UTC, Werfit requested changes
Not everywhere required `onDelete: 'CASCADE'`, f. e. relation between user and its mentor. If mentor account is removed, it doesn't mean mentee account must be deleted too

2022-03-24 22:29 UTC, aleksandr-kuharenko approved these changes

2022-03-25 09:46 UTC, Werfit requested changes
remove `console.warn` and `ControlButton` component already has `className="user-control-btn"`, so remove it this class in `user-controllers.tsx`

2022-03-25 10:03 UTC, Werfit approved these changes

2022-03-25 10:03 UTC, merged