#147 Add burger block for sidebar
BinaryStudioAcademy/bsa-winter-2022-growup pull request #160
Opened 2022-03-24 15:15 UTC by deimonbody

2022-03-24 22:30 UTC, aleksandr-kuharenko approved these changes

2022-03-25 09:59 UTC, nikita-remeslov requested changes

2022-03-25 09:59 UTC, nikita-remeslov commented on frontend/src/components/sidebar/styles.scss
> +  width: 65px !important;
why do you use so many `important`?

2022-03-25 09:59 UTC, nikita-remeslov commented on frontend/src/components/sidebar/styles.scss
> +    //2222
?

2022-03-28 06:48 UTC, nikita-remeslov requested changes

2022-03-28 06:48 UTC, nikita-remeslov commented on frontend/src/components/sidebar/styles.scss
> +    display: none !important;
Do you need it?

And all other `!important`

2022-03-28 07:45 UTC, nikita-remeslov approved these changes

2022-03-28 07:45 UTC, merged