#165 Add frontend part-1
BinaryStudioAcademy/bsa-winter-2022-growup pull request #179
Opened 2022-03-27 15:52 UTC by deimonbody

Add front-end part of this task - part 1
Okr info page
Modal for add new objective with keyresults 
Changed store

2022-03-28 07:41 UTC, nikita-remeslov requested changes

2022-03-28 07:41 UTC, nikita-remeslov commented on frontend/src/validation-schemas/okr/okr.validation-schema.ts
> +  //Messages for the objective schema
?

2022-03-29 09:04 UTC, nikita-remeslov requested changes

2022-03-29 09:04 UTC, nikita-remeslov commented on frontend/src/validation-schemas/okr/okr.validation-schema.ts
> +  //Messages for the objective schema
Do you need this comments?

2022-03-29 09:04 UTC, nikita-remeslov commented on frontend/src/components/okr/styles.scss
> +  background-color: #8080801f !important;
Do you really need `!important`

2022-03-29 17:51 UTC, aleksandr-kuharenko approved these changes

2022-03-30 07:42 UTC, nikita-remeslov approved these changes

2022-03-30 07:43 UTC, nikita-remeslov commented
Conflicts

2022-03-30 08:03 UTC, aleksandr-kuharenko approved these changes

2022-03-30 10:51 UTC, merged