Fix/opportunity #174, #177, #170
BinaryStudioAcademy/bsa-winter-2022-growup pull request #191
Opened 2022-03-29 13:53 UTC by twistedomelette

2022-03-29 17:47 UTC, aleksandr-kuharenko requested changes

2022-03-29 17:47 UTC, aleksandr-kuharenko commented on frontend/src/components/skills/rating/skill-rating.tsx
> +} from 'react-bootstrap-icons';
????

2022-03-30 07:44 UTC, nikita-remeslov approved these changes

2022-03-30 07:53 UTC, deimonbody approved these changes

2022-03-30 07:55 UTC, merged