feat/add myOkr, allOkr, styles Okr, State with data. Task 34
BinaryStudioAcademy/bsa-winter-2022-growup pull request #22
Opened 2022-02-11 08:30 UTC by twistedomelette

2022-02-14 09:51 UTC, aleksandr-kuharenko commented on frontend/src/components/okrs/components/tabs-okr/two-tabs.tsx
> +        onSelect={(k:any):any => setKey(k)}
do not use any

2022-02-14 09:51 UTC, aleksandr-kuharenko commented on frontend/src/components/okrs/components/tabs-okr/two-tabs.tsx
> +                const ArrayofObjectives = Objective.filter((el:any) => el.okrId === MyOKR.id);
do not use any

2022-02-14 09:52 UTC, aleksandr-kuharenko commented on frontend/src/components/okrs/components/tabs-okr/two-tabs.tsx
> +            })}
logic is duplicated, reuse

2022-02-14 09:53 UTC, aleksandr-kuharenko commented on frontend/src/store/okr/slice.ts
> +    // {id: number, name:string, ObjectiveId:number}[]
Use interfaces

2022-02-14 10:10 UTC, nikita-remeslov requested changes

2022-02-14 10:10 UTC, nikita-remeslov commented on frontend/src/components/okrs/styles.scss
> +    margin-left: 15px;
ms-3

2022-02-14 10:10 UTC, nikita-remeslov commented on frontend/src/components/okrs/styles.scss
> +    margin-bottom: 15px;
mb-3

2022-02-14 10:10 UTC, nikita-remeslov commented on frontend/src/components/okrs/styles.scss
> +    padding: 8px 15px;
py-2 px-3

2022-02-14 10:10 UTC, nikita-remeslov commented on frontend/src/components/okrs/styles.scss
> +    border-radius: 10px;
rounded

2022-02-14 10:10 UTC, nikita-remeslov commented on frontend/src/components/okrs/styles.scss
> +    border: 2px solid #ff9900;
try to use `border` class

2022-02-14 10:10 UTC, nikita-remeslov commented on frontend/src/components/okrs/styles.scss
> +            "n n re"
If you come back to this code in a month, I don't think you'll remember that grid area name.

2022-02-14 10:10 UTC, nikita-remeslov commented on frontend/src/components/okrs/styles.scss
> +    align-self: start;
align-self-start

2022-02-14 10:10 UTC, nikita-remeslov commented on frontend/src/components/okrs/styles.scss
> +    flex-direction: row;
d-flex flex-row flex-wrap

2022-02-14 10:10 UTC, nikita-remeslov commented
Also fix conflicts

2022-02-14 16:29 UTC, nikita-remeslov commented
Conflcts

2022-02-15 08:15 UTC, nikita-remeslov requested changes

2022-02-15 08:15 UTC, nikita-remeslov commented on frontend/src/store/okr/slice.ts
> +    User: IUser,
`user`, use lowercase

2022-02-15 08:15 UTC, nikita-remeslov commented on frontend/src/store/common/interfaces.ts
> +    ObjectiveId: number
lowercase

2022-02-15 08:15 UTC, nikita-remeslov commented on frontend/src/components/okr/workspace-item.tsx
> +    NumOfKeyResults: number
resultCount

2022-02-15 08:15 UTC, nikita-remeslov commented on frontend/src/components/okr/workspace-item.tsx
> +    NumOfObjectives: number
objectiveCount

2022-02-15 08:15 UTC, nikita-remeslov commented on frontend/src/components/okr/two-tabs.tsx
> +    const OkrList: React.FC<PropTypes> = (props) => (
1 component === 1 file

Also, use can get collection with useSelector and pass it to the OkrList.

2022-02-15 08:15 UTC, nikita-remeslov commented on frontend/src/components/okr/common/interfaces.ts
> +    ObjectiveId: number
lowercase

2022-02-15 10:36 UTC, nikita-remeslov approved these changes
Remove interface duplication. Overall looks good

2022-02-15 10:38 UTC, aleksandr-kuharenko approved these changes

2022-02-15 10:38 UTC, deimonbody approved these changes

2022-02-15 11:18 UTC, twistedomelette commented
Added okr in folder components/ork and change store

2022-02-15 11:18 UTC, merged