#21 Profile page route correction, fixed adaptiveness
BinaryStudioAcademy/bsa-winter-2022-growup pull request #28
Opened 2022-02-14 10:49 UTC by AndriyCh1

2022-02-14 11:09 UTC, nikita-remeslov requested changes

2022-02-14 11:09 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/edit-section/edit-section.scss
> +@media screen and (max-width: 992px) {
bootstrap grid - https://getbootstrap.com/docs/5.0/layout/breakpoints/#min-width

2022-02-14 11:09 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/profile-info.scss
> +@media screen and (max-width: 1200px) {
bootstrap grid

2022-02-14 11:09 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/profile-main/profile-main.scss
> +@media screen and (max-width: 1200px) {
bootstrap grid

2022-02-14 16:28 UTC, nikita-remeslov approved these changes

2022-02-15 07:41 UTC, aleksandr-kuharenko approved these changes

2022-02-15 07:41 UTC, merged