#47 3 notifications in page
BinaryStudioAcademy/bsa-winter-2022-growup pull request #41
Opened 2022-02-16 10:58 UTC by Pavel1066

2022-02-16 15:06 UTC, aleksandr-kuharenko requested changes

2022-02-16 15:06 UTC, aleksandr-kuharenko commented on frontend/src/components/main-page/notifications/notifications.tsx
> +    const to = viewAll ? notificationsData.length : 3;
3 is magic number. Create constant

2022-02-16 16:24 UTC, aleksandr-kuharenko approved these changes

2022-02-17 08:34 UTC, nikita-remeslov approved these changes

2022-02-17 08:34 UTC, merged