#37-New/add edit opportunities
BinaryStudioAcademy/bsa-winter-2022-growup pull request #43
Opened 2022-02-16 17:24 UTC by deimonbody

Page opportunities version 1.0

2022-02-16 19:15 UTC, AndriyCh1 approved these changes

2022-02-16 21:53 UTC, aleksandr-kuharenko requested changes

2022-02-16 21:53 UTC, aleksandr-kuharenko commented on backend/src/api/routes/index.ts
> +  app.use('/company/opportunities', opportunitiesRoute);
```suggestion
  app.use('/api/company/opportunities', opportunitiesRoute);
```

2022-02-16 21:53 UTC, aleksandr-kuharenko commented on backend/src/api/routes/opportunities-route.ts
> +export default router;
please format this file

2022-02-16 21:53 UTC, aleksandr-kuharenko commented on backend/src/data/seed-data/opp_tag.data.ts
> +export const opp_tags = [{},{},{}];
is it still needed?

2022-02-16 21:53 UTC, aleksandr-kuharenko commented on backend/src/data/seeders/index.ts
> +Connection();
add try...catch block and log error message

2022-02-16 21:53 UTC, aleksandr-kuharenko commented on frontend/package.json
> +    "uuid": "^8.3.2"
remove this lib if it is not used anywhere

2022-02-16 21:53 UTC, aleksandr-kuharenko commented on frontend/package.json
> +    "@types/uuid": "^8.3.4",
same

2022-02-17 08:39 UTC, nikita-remeslov requested changes

2022-02-17 08:39 UTC, nikita-remeslov commented on frontend/src/components/opportunities-page/OpportunityModal.tsx
> +// import { fetchAddNewOpp } from 'store/opportunities/actions';
Do you need these comments?

2022-02-17 08:39 UTC, nikita-remeslov commented on frontend/src/components/opportunities-page/styles.scss
> +    //     cursor: pointer;
The same

2022-02-17 08:39 UTC, nikita-remeslov commented on frontend/src/store/store.ts
> +// Inferred type: {posts: PostsState, comments: CommentsState, users: UsersState}
the same

2022-02-17 20:12 UTC, nikita-remeslov commented
Fix comment for this PR

2022-02-19 15:09 UTC, nikita-remeslov commented
Fix conflicts

2022-02-22 08:19 UTC, nikita-remeslov requested changes

2022-02-22 08:19 UTC, nikita-remeslov commented on frontend/src/components/main-page/opportunities/opportunities.scss
> +    // transition: all 0.5s linear;
Remove it if you don't need this

2022-02-22 08:19 UTC, nikita-remeslov commented on frontend/src/components/main-page/opportunities/opportunityList.tsx
> +    {
Move mock to redux

2022-02-22 08:19 UTC, nikita-remeslov commented on frontend/src/components/opportunities-page/Follow.tsx
> +interface Props extends IOpportunity {}
I think it should work like this `interface Props extends IOpportunity`

2022-02-22 08:19 UTC, nikita-remeslov commented on frontend/src/components/opportunities-page/opportunitiesPageItem.tsx
> +interface Props extends IOpportunity {}
same

2022-02-22 08:19 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/profile-info.scss
> +@import 'src/assets/scss/styles';
check my comments about styles in our team chat. Also if you use imports, please use alias if needed

2022-02-22 08:19 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/tabs/tabs.scss
> +@import 'src/assets/scss/styles';
the same, remove this changes

2022-02-22 10:22 UTC, aleksandr-kuharenko requested changes

2022-02-22 10:22 UTC, aleksandr-kuharenko commented on backend/src/api/routes/opportunities-route.ts
> +  run((_) => getOpportunities()),
use companyId from request to get only opportunities for the needed company

2022-02-22 10:22 UTC, aleksandr-kuharenko commented on backend/src/api/routes/opportunities-route.ts
> +  run((req) => createOpportunities(req.body.opportunities)),
use companyId from request to create opportunities under the needed company
and userId as well

2022-02-22 10:22 UTC, aleksandr-kuharenko commented on backend/src/data/seed-data/opp-tag.data.ts
> +export const opp_tags = [{}, {}, {}];
it is not used anywhere

2022-02-22 10:22 UTC, aleksandr-kuharenko commented on backend/src/services/opportunity.service.ts
> +  });
use real companyId and userId from token

2022-02-22 10:22 UTC, aleksandr-kuharenko commented on backend/src/services/opportunity.service.ts
> +  });
use real companyId and userId from token

2022-02-22 13:44 UTC, aleksandr-kuharenko requested changes

2022-02-22 13:44 UTC, aleksandr-kuharenko commented on backend/src/services/opportunity.service.ts
> +  } as FindManyOptions);
As I understood, this service should return all opportunities in the company. You do not need user here

2022-02-22 19:49 UTC, nikita-remeslov requested changes
Overall looks good

2022-02-22 19:49 UTC, nikita-remeslov commented on frontend/src/components/main-page/opportunities/opportunityList.tsx
> +import './opportunities.scss';
rename to `styles.scss`

2022-02-22 19:49 UTC, nikita-remeslov commented on frontend/src/components/opportunities-page/opportunitiesPage.tsx
> +  // const showModalHandler = ():void=> { dispatch(opportunitiesActions.showModal()); };
Do you need these comments?

2022-02-22 20:26 UTC, nikita-remeslov approved these changes

2022-02-23 05:16 UTC, aleksandr-kuharenko approved these changes

2022-02-23 05:59 UTC, AndriyCh1 approved these changes

2022-02-23 06:12 UTC, merged