#51 Update routing
BinaryStudioAcademy/bsa-winter-2022-growup pull request #44
Opened 2022-02-16 19:48 UTC by Karyna-Kharina

2022-02-16 21:47 UTC, aleksandr-kuharenko commented on frontend/src/store/auth/slice.ts
> +  isAuthenticated: !!storage.getItem('token'),
we have this value in Enum

2022-02-17 08:46 UTC, nikita-remeslov requested changes
With your implementation, you can create 2 separate components with routes.
And after that use it in the App.tsx

Example: 
![image](https://user-images.githubusercontent.com/78347072/154438192-3590516d-cbb2-41ab-bd2e-f3598c56213c.png)

Also if you go to the login page and you have a valid token in the store, we need to redirect the user to the main page `/`

And currently, if I have an admin role, I can not go to the login page if I authorized because in admin routes we don't have `/login`

2022-02-17 14:56 UTC, nikita-remeslov requested changes

2022-02-17 14:56 UTC, nikita-remeslov commented on frontend/src/components/app/app.tsx
> +            <Header />
We can move it to UserRouting component

2022-02-17 14:56 UTC, nikita-remeslov commented on frontend/src/components/app/app.tsx
> +            <main className="main-container w-100 px-5 pt-3 pb-5">
move container to UserRouting

2022-02-17 14:56 UTC, nikita-remeslov commented on frontend/src/components/app/app.tsx
> +            <div className="w-100">
Move container to AdmitRouting

2022-02-17 14:56 UTC, nikita-remeslov commented on frontend/src/components/app/admin-routing.tsx
> +      adminRoutes.map(({ path, element }: IRoute) =>
We need to add here AppRoutes. Because in this case if Admin `isAutorized === true`, he will not have login page

2022-02-17 20:11 UTC, nikita-remeslov approved these changes
Fix conflict and 2 comments. 
All other code looks good

2022-02-17 20:11 UTC, nikita-remeslov commented on frontend/src/helpers/token/is-valid-token.ts
> +  } catch (err) {
As I understand you can use catch without err, because you don't use it

2022-02-17 20:11 UTC, nikita-remeslov commented on frontend/src/components/app/app.tsx
>      <div>
use Fragment

2022-02-18 08:11 UTC, nikita-remeslov approved these changes

2022-02-18 08:11 UTC, merged