#50  Adding career path
BinaryStudioAcademy/bsa-winter-2022-growup pull request #46
Opened 2022-02-17 10:44 UTC by Werfit

2022-02-17 11:49 UTC, Karyna-Kharina commented on backend/src/api/controllers/career-path.controller.ts
> +  await asyncForEach(async ([name, value]) => {
remove nesting and move each asyncForEach() function call to separate functions

2022-02-17 11:49 UTC, Karyna-Kharina commented on backend/src/data/migrations/1644920948847-add-column-name-domain-level.ts
> +export class addColumnNameDomainLevel1644920948847
are such function names allowed?

2022-02-17 11:49 UTC, Karyna-Kharina commented on backend/src/data/migrations/1644929911066-skill-fields-update.ts
> +    // await queryRunner.query(`ALTER TABLE "skill" DROP COLUMN "name"`);
remove commented code

2022-02-17 11:49 UTC, Karyna-Kharina commented on backend/src/data/seed-data/skills.data.ts
> +    name: 'HTML5',
move skill names to enum

2022-02-17 11:49 UTC, Karyna-Kharina commented on backend/src/data/seeders/skills.seeder.ts
> +// import { PermissionType } from 'growup-shared';
remove commented code

2022-02-17 11:53 UTC, aleksandr-kuharenko requested changes

2022-02-17 11:53 UTC, aleksandr-kuharenko commented on backend/src/data/migrations/1644929911066-skill-fields-update.ts
> +    // await queryRunner.query(`ALTER TABLE "skill" DROP COLUMN "name"`);
?

2022-02-17 11:53 UTC, aleksandr-kuharenko commented on backend/src/data/seeders/skills.seeder.ts
> +// import { PermissionType } from 'growup-shared';
```suggestion
```

2022-02-17 11:53 UTC, aleksandr-kuharenko commented on backend/src/api/controllers/career-path.controller.ts
> +    asyncForEach(async ([name, value]) => {
```suggestion
    await asyncForEach(async ([name, value]) => {
```

2022-02-17 11:53 UTC, aleksandr-kuharenko commented on backend/src/api/controllers/career-path.controller.ts
> +      asyncForEach(async (skill) => {
```suggestion
      await asyncForEach(async (skill) => {
```

2022-02-22 08:37 UTC, nikita-remeslov approved these changes

2022-02-22 08:38 UTC, aleksandr-kuharenko requested changes

2022-02-22 08:38 UTC, aleksandr-kuharenko commented on backend/src/api/routes/career-path.ts
> +    const company = await getCompany();
find company with id from token. req.companyId

2022-02-22 08:38 UTC, aleksandr-kuharenko commented on backend/src/api/routes/index.ts
> +  app.use('/company', companyRoute);
```suggestion
```

2022-02-22 09:31 UTC, aleksandr-kuharenko approved these changes

2022-02-22 09:31 UTC, merged