#68 Interests block is not filled with purple in Profile Settings
BinaryStudioAcademy/bsa-winter-2022-growup pull request #48
Opened 2022-02-17 14:38 UTC by Karyna-Kharina

2022-02-17 15:51 UTC, Pavel1066 approved these changes

2022-02-17 20:04 UTC, nikita-remeslov requested changes
Looks good, just need to update styles. Try to use bootstrap classes instead of custom styles

2022-02-17 20:04 UTC, nikita-remeslov commented on frontend/src/components/profile-settings/steps/interests-block.scss
> +@import 'src/assets/css/styles';
Merge dev and use `~assets/scss/utils`

2022-02-17 20:04 UTC, nikita-remeslov commented on frontend/src/components/profile-settings/steps/interests-block.scss
> +    background-color: #463da8;
$gu-blue from utils

2022-02-17 20:04 UTC, nikita-remeslov commented on frontend/src/components/profile-settings/steps/interests-block.scss
> +    margin: 0;
m-0

2022-02-17 20:04 UTC, nikita-remeslov commented on frontend/src/components/profile-settings/steps/interests-block.scss
> +    border-radius: 0;
border-0

2022-02-17 20:04 UTC, nikita-remeslov commented on frontend/src/components/profile-settings/steps/interests-block.scss
> +      color: #f6f7f9;
$gu-white

2022-02-17 20:04 UTC, nikita-remeslov commented on frontend/src/components/profile-settings/steps/interests-block.scss
> +    color: #f6f7f9;
$gu-white

also you can use text-gu-white

2022-02-17 20:04 UTC, nikita-remeslov commented on frontend/src/components/profile-settings/steps/interests-block.scss
> +      position: relative;
position-relative

2022-02-17 20:04 UTC, nikita-remeslov commented on frontend/src/components/profile-settings/styles.scss
> +  justify-content: space-between;
`justify-content-between ` bootstrap class

2022-02-18 08:13 UTC, nikita-remeslov approved these changes

2022-02-18 08:13 UTC, merged