#72 User Logout
BinaryStudioAcademy/bsa-winter-2022-growup pull request #55
Opened 2022-02-18 16:38 UTC by Werfit

2022-02-18 17:03 UTC, aleksandr-kuharenko approved these changes

2022-02-19 15:14 UTC, nikita-remeslov requested changes
I think we need to add logout for admin too.
Also, we can add admin image to the header

2022-02-19 20:59 UTC, Werfit commented
Besides adding ability to logout for admin, I found code that breaks admin page(it is restricted in size and can not be shown fully). I didn't fix it, because if I start, than I believe it will take me to fixing all of the styles(since it will take a lot of time for me to fix styles). I fixed RoleTypes as well, because simple importing it from **growup-shared** would raise error and lead to bugs.

2022-02-20 17:26 UTC, aleksandr-kuharenko approved these changes

2022-02-21 09:56 UTC, nikita-remeslov approved these changes

2022-02-21 09:56 UTC, merged