#85 Create common components
BinaryStudioAcademy/bsa-winter-2022-growup pull request #68
Opened 2022-02-22 10:17 UTC by Karyna-Kharina

2022-02-22 10:57 UTC, Pavel1066 commented on frontend/src/components/common/auto-complete/auto-complete.tsx
> +import { useState } from '../../../hooks/hooks';
change to ''hooks/hooks'

2022-02-22 10:57 UTC, Pavel1066 commented on frontend/src/components/profile-settings/steps/first-step.tsx
> +import { TextField } from '../../common/common';
change to ''components/common/common'

2022-02-22 19:41 UTC, nikita-remeslov requested changes
Overall looks good, fix comments and we can merge it

2022-02-22 19:41 UTC, nikita-remeslov commented on frontend/package.json
> +    "@types/react-bootstrap-typeahead": "^5.1.8",
lock lib

2022-02-22 19:41 UTC, nikita-remeslov commented on frontend/src/components/common/auto-complete/styles.scss
> +@import 'src/assets/scss/utils';
Use alias `~assets/scss/utils`

2022-02-22 19:41 UTC, nikita-remeslov commented on frontend/src/components/common/modal/styles.scss
> +@import 'src/assets/scss/utils';
same

2022-02-22 19:41 UTC, nikita-remeslov commented on frontend/src/components/common/modal/styles.scss
> +@media (max-width: 576px) {
try to use breakpoint from bootstrap

2022-02-23 10:24 UTC, nikita-remeslov approved these changes

2022-02-23 10:26 UTC, aleksandr-kuharenko approved these changes

2022-02-23 10:26 UTC, merged