Createad scaffold for Mentor/Mentee Home Page
BinaryStudioAcademy/bsa-winter-2022-growup pull request #7
Opened 2022-02-08 11:31 UTC by deimonbody

Created scaffold for Mentor/Mentee Home Page.Added 2 main blocks:
-Notifications: Some notification,type label itc.
-Recomendded opportunities : Some cart of opportunities

2022-02-08 15:34 UTC, nikita-remeslov requested changes
discussed need changes

2022-02-09 10:38 UTC, nikita-remeslov requested changes
discussed, need changes

2022-02-09 18:32 UTC, nikita-remeslov requested changes
Overall looks good, need to fix a few comments.

2022-02-09 18:32 UTC, nikita-remeslov commented on frontend/package.json
> +    "react-bootstrap-icons": "^1.7.2",
lock lib

2022-02-09 18:32 UTC, nikita-remeslov commented on frontend/src/components/main-page/icons/approveSkills.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path fill="white" d="M288 358.3c13.98-8.088 17.53-30.04 28.88-41.39c11.35-11.35 33.3-14.88 41.39-28.87c7.98-13.79 .1658-34.54 4.373-50.2
image naming better do with `-`
`approve-skill.svg`

2022-02-09 18:32 UTC, nikita-remeslov commented on frontend/src/components/main-page/notifications/notification.scss
> +        font-size:0.8rem;
pull develop and use our default font size

2022-02-09 18:32 UTC, nikita-remeslov commented on frontend/src/components/main-page/notifications/notification.scss
> +        max-width:600px;
use bootstrap grid - https://getbootstrap.com/docs/4.0/layout/grid/

2022-02-09 18:32 UTC, nikita-remeslov commented on frontend/src/components/main-page/interfaces/ILabaleData.tsx
> +    typeTitle?:string,
Do you need `typeTitle`? Because I can't find where you use it

2022-02-09 18:32 UTC, nikita-remeslov commented on frontend/src/components/main-page/notifications/label.tsx
> +const Label = ( { type } :ILabelData):ReactElement=>{
Props extends ILabelData

2022-02-10 10:31 UTC, nikita-remeslov approved these changes

2022-02-10 10:54 UTC, AndriyCh1 approved these changes

2022-02-10 10:54 UTC, merged