Career Path Response
BinaryStudioAcademy/bsa-winter-2022-growup pull request #82
Opened 2022-02-28 12:56 UTC by Werfit

Career path is changed due to request of the teammate

2022-02-28 15:26 UTC, aleksandr-kuharenko requested changes

2022-02-28 15:26 UTC, aleksandr-kuharenko commented on backend/src/api/controllers/career-path.controller.ts
> +    }));
move to mappers

2022-02-28 15:26 UTC, aleksandr-kuharenko commented on backend/src/api/controllers/career-path.controller.ts
> +  const rootLevel = (await getDomainLevels(domain)) as DomainLevelResponse;
getDomainLevels returns type `DomainLevel`. Do not use `as`, return correct format and use actual interface everywhere

2022-02-28 15:26 UTC, aleksandr-kuharenko commented on backend/src/api/controllers/career-path.controller.ts
> +    ) as unknown as Skill[];
try to not use `as`

2022-03-01 10:08 UTC, aleksandr-kuharenko approved these changes

2022-03-10 13:03 UTC, AndriyCh1 approved these changes

2022-03-10 13:06 UTC, merged