#99 Add Career journey and Education in Profile Page
BinaryStudioAcademy/bsa-winter-2022-growup pull request #85
Opened 2022-03-11 10:29 UTC by Karyna-Kharina

2022-03-11 10:45 UTC, AndriyCh1 approved these changes

2022-03-11 12:26 UTC, aleksandr-kuharenko requested changes

2022-03-11 12:26 UTC, aleksandr-kuharenko commented on frontend/package.json
> +    "react-datepicker": "^4.6.0",
```suggestion
    "react-datepicker": "4.6.0",
```

2022-03-14 08:53 UTC, nikita-remeslov requested changes
Overall looks good, fix few comments and we can merge this PR

2022-03-14 08:53 UTC, nikita-remeslov commented on frontend/src/common/types/http/http-options.type.ts
> +  payload?: BodyInit | null;
not sure, but `null` is redundant

2022-03-14 08:53 UTC, nikita-remeslov commented on frontend/src/react-app-env.d.ts
> +declare module 'react-datepicker';
I think we can use https://www.npmjs.com/package/@types/react-datepicker

2022-03-14 11:40 UTC, nikita-remeslov approved these changes

2022-03-14 11:42 UTC, merged