New/profile page
BinaryStudioAcademy/bsa-winter-2022-growup pull request #9
Opened 2022-02-08 14:27 UTC by AndriyCh1

2022-02-08 15:09 UTC, nikita-remeslov requested changes
discussed need changes

Update: comment for another PR

2022-02-09 09:39 UTC, nikita-remeslov commented on frontend/package.json
> +    "react-bootstrap-icons": "^1.7.2",
Should lock lib
`"react-bootstrap-icons": "1.7.2"`

2022-02-09 09:54 UTC, nikita-remeslov requested changes
Try to use default styles for buttons - https://getbootstrap.com/docs/4.0/components/buttons/

Also need to add mobile view -
![image](https://user-images.githubusercontent.com/78347072/153171943-b8a70c58-9a70-4d8f-924c-15c52cb792cc.png)

2022-02-09 09:54 UTC, nikita-remeslov commented on frontend/src/assets/css/styles.scss
> +  // align-items: center;
If you don't use this styles, better to remove it

2022-02-09 09:54 UTC, nikita-remeslov commented on frontend/src/components/app/app.tsx
> +// import logo from 'assets/img/logo.svg';
Remove if you don't need this

2022-02-09 09:54 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/add-section/add-section.scss
> +.add-section {
Try to use bootstrap classes instead of custom styles. You can remove 80% of these styles and use bootstrap.

2022-02-09 09:54 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/career-card/career-card.scss
> +.career-card {
The same, use bootstrap classes

2022-02-09 09:54 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/edit-section/edit-section.scss
> +.edit-section {
Use bootstrap

2022-02-09 09:54 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/education-card/education-card.scss
> +.education-card {
Bootstrap

2022-02-09 09:54 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/profile-main/profile-main.tsx
> +interface Education {
You should move it to profile-info/interface, and after that import this interface and extends it in props and other interfaces.

We should use DRY and don't duplicate our code.

2022-02-09 09:54 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/tabs/tabs.scss
> +.tabs {
Bootstrap

2022-02-09 09:54 UTC, nikita-remeslov commented on frontend/src/components/profile/components/profile-info/tag/tag.scss
> +.tag {
Bootstrap

2022-02-11 08:03 UTC, nikita-remeslov approved these changes
Looks good

2022-02-11 11:11 UTC, deimonbody approved these changes

2022-02-11 11:32 UTC, merged