New/skill endpoints task #81 and #42
BinaryStudioAcademy/bsa-winter-2022-growup pull request #91
Opened 2022-03-11 18:58 UTC by twistedomelette

Made the interaction of the front and the back, you can delete, add, change the skill, as well as sort by the criterion

2022-03-11 20:14 UTC, aleksandr-kuharenko requested changes

2022-03-11 20:14 UTC, aleksandr-kuharenko commented on frontend/src/components/skills/rating/skill-rating.tsx
> +            type: 'Soft skills',
remove hardcode

2022-03-11 20:14 UTC, aleksandr-kuharenko commented on backend/src/services/skill.service.ts
> +  body: any,
do not use any

2022-03-11 20:14 UTC, aleksandr-kuharenko commented on backend/src/services/skill.service.ts
> +  const skills: any = [];
any

2022-03-11 20:14 UTC, aleksandr-kuharenko commented on backend/src/services/skill.service.ts
> +      type: type,
```suggestion
      name,
      type,
```

2022-03-11 20:14 UTC, aleksandr-kuharenko commented on backend/src/services/skill.service.ts
> +    const isStarred = userSkillInstance[index].isStarred;
```suggestion
    const { selfRating, mentorRating, reviewRating, isStarred  } = userSkillInstance[index];
```

2022-03-11 20:14 UTC, aleksandr-kuharenko commented on backend/src/services/skill.service.ts
> +  body: any,
use word 'data' instead of 'body'

2022-03-11 20:14 UTC, aleksandr-kuharenko commented on backend/src/services/skill.service.ts
> +    id: id,
```suggestion
    id,
```

2022-03-11 20:14 UTC, aleksandr-kuharenko commented on backend/src/api/routes/company-route.ts
> +  // validatePermissions([RoleType.ADMIN]),
```suggestion
  validatePermissions([RoleType.ADMIN]),
```

2022-03-11 20:14 UTC, aleksandr-kuharenko commented on backend/src/services/skill.service.ts
> +    const ratings = [body[1].rating[0], body[1].rating[1], body[1].rating[2]];
unreadable

2022-03-14 09:34 UTC, nikita-remeslov requested changes

2022-03-14 09:34 UTC, nikita-remeslov commented on backend/src/services/skill.service.ts
> +  isStarred: boolean | any;
any? We don't use any

2022-03-14 09:34 UTC, nikita-remeslov commented on backend/src/services/skill.service.ts
> +  console.log(skillsWithRating);
remove console.log

2022-03-14 09:34 UTC, nikita-remeslov commented on backend/src/services/skill.service.ts
> +  const skills: any = [];
any

2022-03-14 09:34 UTC, nikita-remeslov commented on backend/src/services/skill.service.ts
> +  console.log('s');
console.log

2022-03-14 09:34 UTC, nikita-remeslov commented on backend/src/services/skill.service.ts
> +  console.log(skills);
console.log

2022-03-14 09:34 UTC, nikita-remeslov commented on backend/src/services/skill.service.ts
> +  data: any,
any

2022-03-14 09:34 UTC, nikita-remeslov commented on backend/src/services/skill.service.ts
> +    console.log(data);
console.log

2022-03-14 09:34 UTC, nikita-remeslov commented on frontend/src/common/interfaces/skill/skill.ts
> +  rating?: any;
any

2022-03-14 09:34 UTC, nikita-remeslov commented on frontend/src/store/company/actions.ts
> +    console.warn(result);
Do you need it?

2022-03-14 09:34 UTC, nikita-remeslov commented on frontend/src/store/skill/slice.ts
> +// import { ISkill } from 'common/interfaces/skill/skill';
remove if you don't need this

2022-03-14 16:07 UTC, aleksandr-kuharenko approved these changes

2022-03-14 16:12 UTC, AndriyCh1 approved these changes

2022-03-14 16:45 UTC, nikita-remeslov approved these changes

2022-03-14 16:45 UTC, merged