#98 Fix/route user to profile settings
BinaryStudioAcademy/bsa-winter-2022-growup pull request #98
Opened 2022-03-14 07:16 UTC by deimonbody

2022-03-14 09:35 UTC, AndriyCh1 commented on backend/src/services/user.service.ts
> +  const userQuizRepositiore = getCustomRepository(User_QuizCategoryRepository);
fix name of "userQuizRepositiore"

2022-03-14 09:36 UTC, AndriyCh1 commented on frontend/src/components/sidebar/sidebar.tsx
> +import _ from 'lodash';
remove import if you don`t use it

2022-03-14 09:54 UTC, AndriyCh1 approved these changes

2022-03-14 10:05 UTC, nikita-remeslov requested changes

2022-03-14 10:05 UTC, nikita-remeslov commented on frontend/src/components/opportunities-page/opportunitiesPage.tsx
>  import OpportunityPageItem from './opportunitiesPageItem';
fix file name

2022-03-14 10:05 UTC, nikita-remeslov commented on frontend/src/components/profile-settings/steps/second-step.tsx
> +      {isCompleteTest ? (
Do we need 2 ternary operators?

2022-03-14 10:05 UTC, nikita-remeslov commented on frontend/src/components/profile/profile.tsx
> +    if (user) {
try to simplify this logic. Very hard to understand what is going on here. You use `if` then `ternary operator` then `ternary operator`

2022-03-14 16:19 UTC, nikita-remeslov commented
Conflicts @deimonbody

2022-03-15 10:24 UTC, nikita-remeslov approved these changes

2022-03-15 10:24 UTC, merged